services:
  vitaes-db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vitaes
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  vitaes-redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=secure-password
    command: ['redis-server', '--requirepass', '$$REDIS-PASSWORD']
    healthcheck:
      test: ['CMD-SHELL', 'redis_cli -a $$REDIS_PASSWORD ping | grep PONG']
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
volumes:
  db-data:
  redis-data:
