services:
  vitaes-db:
    image: postgres
    restart: always
    user: postgres 
    volumes:
      - db-data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=vitaes
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  db-data:
