packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  '@types/node': ^24.9.1
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  hono: ^4.8.2
  tsdown: ^0.16.5
  typescript: ^5.8.2
  vitest: 4.0.2
  zod: ^4.1.11
