import type { Metadata } from 'next'
// import { OpenPanelComponent } from '@openpanel/nextjs'
import '@/styles/globals.css'
// import { env } from '@/env'
// import { auth } from '@/server/auth'
// import { headers } from 'next/headers'
import { PostHogProvider } from '@/providers/posthog-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await auth.api.getSession({
  //   headers: await headers(),
  // })

  return (
    <PostHogProvider>
      {/* <OpenPanelComponent
        clientId={env.OPEN_PANEL_CLIENT_ID}
        clientSecret={env.OPEN_PANEL_CLIENT_SECRET}
        apiUrl={env.OPEN_PANEL_API_URL}
        trackScreenViews={true}
        trackAttributes={true}
        trackOutgoingLinks={true}
        profileId={session?.user?.id}
      /> */}
      {children}
    </PostHogProvider>
  )
}
