import {
  AtSign,
  Book,
  Briefcase,
  DraftingCompass,
  FileCheck,
  Gamepad2,
  GraduationCap,
  HandHeart,
  Languages,
  Medal,
  PencilRuler,
  Scroll,
  UserRound,
  Users,
} from 'lucide-react'

export const sections = [
  { id: 'personal', title: 'Personal Information', icon: UserRound },
  { id: 'summary', title: 'Summary', icon: Scroll },
  { id: 'profiles', title: 'Profiles', icon: AtSign },
  { id: 'work', title: 'Work Experience', icon: Briefcase },
  { id: 'volunteer', title: 'Volunteer Experience', icon: HandHeart },
  { id: 'education', title: 'Education', icon: GraduationCap },
  { id: 'awards', title: 'Awards', icon: Medal },
  { id: 'certificates', title: 'Certificates', icon: FileCheck },
  { id: 'publications', title: 'Publications', icon: Book },
  { id: 'skills', title: 'Skills', icon: DraftingCompass },
  { id: 'languages', title: 'Languages', icon: Languages },
  { id: 'interests', title: 'Interests', icon: Gamepad2 },
  { id: 'references', title: 'References', icon: Users },
  { id: 'projects', title: 'Projects', icon: PencilRuler },
]
